#!/usr/bin/env python3


from time import sleep
from wallpaper import set_random_wallpaper
from config import config
from connection import wait_for_connection


if __name__ == '__main__':
    while True:
        wait_for_connection()
        set_random_wallpaper()
        sleep(config['interval'])
