#!/usr/bin/env python3


from time import sleep
import tempfile
from wallpaper import set_random_wallpaper
from config import config


if __name__ == '__main__':
    while True:
        set_random_wallpaper(tempfile.gettempdir())
        sleep(config['interval'])
