#!/usr/bin/env python3


from time import sleep
import tempfile
from wallpaper import set_random_wallpaper


if __name__ == '__main__':
    while True:
        set_random_wallpaper(tempfile.gettempdir())
        sleep(30)
