name: Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libwayland-dev libx11-dev
      - name: Build
        run: go build .
      - uses: actions/upload-artifact@v4
        with:
          name: "randwall_${{ runner.os }}"
          path: randwall*

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: randwall_Linux
          path: dist/linux
      - run: chmod +x dist/linux/randwall
      - run: tar -pczvf linux.tar.gz -C dist/linux randwall
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux.tar.gz
          asset_name: randwall_standalone_linux-x64.tar.gz
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@v4
        with:
          name: randwall_macOS
          path: dist/macos
      - run: chmod +x dist/macos/randwall
      - run: tar -pczvf macos.tar.gz -C dist/macos randwall
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos.tar.gz
          asset_name: randwall_standalone_macos-x64.tar.gz
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@v4
        with:
          name: randwall_Windows
          path: dist/windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows/randwall.exe
          asset_name: randwall_standalone_windows-x64.exe
          asset_content_type: application/octet-stream
